#!/usr/bin/env python3
"""C.2.b demographic significance, by the slope-sufficiency route scope §5 pre-registered.

The chapter cannot use PROTOCOL §4.2.1's decomposition route in the usual way: the largest poolable
stratum is 2, so there is no pooled elasticity. What it has instead is one extreme-treatment estimate
inside the registered SDT window — Ebenstein, Hazan and Simhon's kibbutz privatisation — and the real
price series built by `source/build/318_c2b_child_price_index.py`. That is enough for slope
sufficiency: did the exposure move in the right direction, and by enough?

The elasticity, and why it is generous to the hypothesis
-------------------------------------------------------
The kibbutz reform moved parents from bearing ~0% of the cost of a child to ~100% of it, and lifetime
fertility fell 0.59 children, about 20% of the 3-child mean. Read as a +100% price change that is an
arc elasticity near -0.2. Three reasons it is an UPPER bound, stated rather than buried:

  * the authors themselves warn the elasticity "may not be constant", and note that prior studies
    move price "by a tiny fraction of the cost of raising a child";
  * a shift from full collective subsidy to full private cost is not the marginal price change a CPI
    series measures, so applying it to a 10-130% index move extrapolates far outside the design;
  * it is one MODERATE-risk study of an unusual population.

Two computations, and their difference is the finding
-----------------------------------------------------
ENDPOINT applies the elasticity to the whole-window price change, which is how a demsig share is
normally computed. TIMING applies it decade by decade and sums, so a decade in which the real price
FELL contributes a fertility RISE. `compute-how-the-decline-is-distributed` and
`endpoint-test-nets-a-hump-to-nothing`: a mechanism that moves only in the years when the outcome was
flat explains little, however large its whole-window number looks.

Usage: python3 source/analysis/c2b_demographic_significance.py
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "output" / "tables"
LOGS = ROOT / "literature" / "search-logs"

ELASTICITY = -0.2
ELASTICITY_SOURCE = ("Ebenstein, Hazan & Simhon (2015), Israeli kibbutz privatisation: ~0% -> ~100% "
                     "parental cost share, lifetime fertility -0.59 children = ~20% of the 3-child "
                     "mean. Arc elasticity ~ -0.2, used as an UPPER bound.")
ARMS = ["arm_long_run_1967_equal", "arm_with_education_equal", "arm_with_education_usda",
        "arm_education_only_equal", "arm_without_education_equal"]


def main():
    rows = list(csv.DictReader((TABLES / "child-cost-direct-price-index.csv").open()))

    def num(r, k):
        try:
            return float(r.get(k, ""))
        except (TypeError, ValueError):
            return None

    tfr = {int(r["year"]): num(r, "us_tfr") for r in rows if num(r, "us_tfr") is not None}
    series = {a: {int(r["year"]): num(r, a) for r in rows if num(r, a) is not None} for a in ARMS}
    series = {a: s for a, s in series.items() if s}
    if not series:
        raise SystemExit("no price arms found — run source/build/318_c2b_child_price_index.py first")

    ty = sorted(tfr)
    t0, t1 = max(min(ty), 1967), max(ty)
    obs_pct = (tfr[t1] / tfr[t0] - 1.0) * 100.0

    def observed_over(y0, y1):
        """The fertility change across the SAME years the arm covers."""
        a = min((y for y in tfr if y >= y0), default=None)
        b = max((y for y in tfr if y <= y1), default=None)
        if a is None or b is None or b <= a:
            return None, None, None
        return (tfr[b] / tfr[a] - 1.0) * 100.0, a, b

    L = ["# C.2.b — demographic significance (slope sufficiency)", "",
         "Generated by `source/analysis/c2b_demographic_significance.py`. Do not edit by hand.", "",
         f"**Observed US fertility change {t0}–{t1}: TFR {tfr[t0]:.2f} → {tfr[t1]:.2f}, "
         f"{obs_pct:+.1f}%.**", "",
         "## The elasticity", "", f"`{ELASTICITY}` — {ELASTICITY_SOURCE}", "",
         "It is used because it is the only estimate the chapter has inside its registered SDT "
         "window. Every number below inherits its weaknesses, and the two computations differ by "
         "more than the elasticity is precise to.", "",
         "## Endpoint: the whole-window price change", "",
         "Each arm's share is computed against the fertility change over **its own window**. The "
         "tuition series begin in 1978, and dividing a 1978-onward price effect by the fall from "
         "1967 would credit the mechanism with the 1970s — the decade holding most of the net "
         "decline, and the one in which the real price of children FELL.", "",
         "| arm | window | real price change | implied Δfertility | observed Δ, same window | "
         "share |", "|---|---|---|---|---|---|"]
    endpoint, timing = {}, {}
    for a, s in series.items():
        ys = sorted(s)
        pc = (s[ys[-1]] / s[ys[0]] - 1.0) * 100.0
        implied = ELASTICITY * pc
        own, oa_, ob_ = observed_over(ys[0], ys[-1])
        endpoint[a] = (implied / own * 100.0) if own else float("nan")
        L.append(f"| `{a.replace('arm_', '')}` | {ys[0]}–{ys[-1]} | {pc:+.1f}% | {implied:+.1f}% | "
                 f"{own:+.1f}% ({oa_}–{ob_}) | **{endpoint[a]:.0f}%** |")

    L += ["", "## Timing: the same elasticity applied decade by decade", "",
          "A decade in which the real price FELL contributes a fertility RISE. Summing across decades "
          "respects that; an endpoint calculation nets it away.", "",
          "| arm | decades | implied fertility change | share of observed fall |", "|---|---|---|---|"]
    for a, s in series.items():
        ys = sorted(s)
        edges = [y for y in range(1970, 2031, 10) if ys[0] <= y <= ys[-1]]
        tot, nd = 0.0, 0
        for x, y in zip([ys[0]] + edges[:-1], edges):
            px = min((k for k in s if k >= x), default=None)
            py = min((k for k in s if k >= y), default=None)
            if px is None or py is None or py <= px:
                continue
            tot += ELASTICITY * (s[py] / s[px] - 1.0) * 100.0
            nd += 1
        own, _, _ = observed_over(ys[0], ys[-1])
        timing[a] = (tot / own * 100.0) if own else float("nan")
        L.append(f"| `{a.replace('arm_', '')}` | {nd} | {tot:+.1f}% | **{timing[a]:.0f}%** |")

    L += ["", "## Where the two disagree", "", "| arm | endpoint | timing | gap |", "|---|---|---|---|"]
    for a in series:
        L.append(f"| `{a.replace('arm_', '')}` | {endpoint[a]:.0f}% | {timing[a]:.0f}% | "
                 f"{endpoint[a] - timing[a]:+.0f} pp |")

    best = max(timing.values())
    lr = timing.get("arm_long_run_1967_equal")
    post78, a78, b78 = observed_over(1978, 2023)
    L += ["", "## Verdict input — the two readings, and why they cannot both hold", "",
          "Correcting the window turns this from one number into a contradiction, and the "
          "contradiction is the result.", "",
          f"**Reading 1 — over the whole window, the price barely moved.** On the long-run arm "
          f"(1967–2023, the only one spanning the window from its start, because tuition series "
          f"begin in 1978) the real price of children rose **+10.9%** while TFR fell **-36.8%**. At "
          f"an elasticity of {ELASTICITY} that is **{lr:.0f}%** of the decline. The mechanism is "
          "real and small.", "",
          f"**Reading 2 — after 1978 the price moved enormously and fertility barely responded.** "
          f"US TFR fell only **{post78:+.1f}%** between {a78} and {b78}, while the education-bearing "
          f"arms of the price index rose 79–205% in real terms. Applying the same elasticity implies "
          f"a fall of 15–41%, i.e. **{best:.0f}%** of what actually happened on the most favourable "
          "arm. The mechanism does not under-predict here; it **over-predicts by two to four "
          "times**.", "",
          "**Both readings cannot be true of the same parameter, and neither helps the hypothesis.** "
          "Either the index overstates the price parents actually face — likely, since what carries "
          "it is college tuition and a K-12 series priced off private schooling, neither of which is "
          "the required outlay most parents meet — or the kibbutz elasticity does not transport, "
          "which its own authors warn about when they say the elasticity 'may not be constant'. On "
          "the reading most generous to the index, the mechanism should have emptied the maternity "
          "wards; on the reading most generous to the elasticity, it accounts for roughly a tenth of "
          "the fall.", "",
          "**Strip education out and the sign flips**: the `without_education` arm falls 16.6% in "
          "real terms, implying fertility should have RISEN. Scope ruling 2 assigns college tuition "
          "largely to C.3.d as chosen quality rather than to C.2.b as a required price, so the "
          "component doing the work is the one this chapter has the weakest claim to.", "",
          "Every number rests on an elasticity from a single MODERATE-risk study of an extreme "
          "treatment in an unusual population, extrapolated to marginal price changes the design "
          "never observed. These bound the mechanism; they do not estimate it.", ""]
    (LOGS / "child-cost-direct-demographic-significance.md").write_text("\n".join(L))
    (TABLES / "child-cost-direct-demsig.json").write_text(json.dumps(
        {"elasticity": ELASTICITY, "elasticity_source": ELASTICITY_SOURCE,
         "observed_pct": obs_pct, "endpoint_share_pct": endpoint,
         "timing_share_pct": timing}, indent=1) + "\n")
    print("\n".join(L))


main()
